name: Create Jira Issue

on:
  issues:
    types: Task

jobs:
  createJiraIssue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira Issue
        with:
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          project: 'SS'
          # Other necessary parameters for the integration
