import requests

JIRA_PROJECT_KEY = "TT"
SUMMARY = "Issue created from GitHub Actions"
DESCRIPTION = "This issue was created automatically using GitHub Actions."

url = f"{JIRA_BASE_URL}/rest/api/2/issue/"
auth = (JIRA_EMAIL, JIRA_API_TOKEN)

issue_data = {
    "fields": {
        "project": {"key": JIRA_PROJECT_KEY},
        "summary": SUMMARY,
        "description": DESCRIPTION,
        "issuetype": {"name": "Task"}
    }
}

response = requests.post(url, json=issue_data, auth=auth)
if response.status_code == 201:
    print("Issue created successfully.")
else:
    print(f"Failed to create issue. Status code: {response.status_code}")
